### PR TITLE
Rspec

### PR DESCRIPTION
**Pull request by craigs40**
For this assignment, we've built tests for the tic tac toe game according to the classes described in the tic tac toe project.

### CODE REVIEW

**Comment by rukundoeric** [comment]
# Status: ⚠️ INVALID ⚠️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] N/A

- ### To Improve
  - [x] [MANDATORY] This PR doesn't follow git-work flow as it is instructed in project specifications. on this project you were supposed to create a merge PR into `development` branch and not `main` branch.
  - [x] [MANDATORY] PR description is not descriptive enough

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Review by DeliceLydia — CHANGES_REQUESTED** [review]
# Changes Requested image


Hello @craigs40 I can see you are putting much effort into this project but
you still have some changes to make

- Your test has some warnings when I run it
test

you can see instances variable you are using while testing was not initialized

- Try to test positive and negative scenarios
examples: you can test if I provide a number that is not between 0-8 what will happen or not try to add some more tests to make your app less guilty

# Happy Coding image

best,

Lydia Ingabire

**Comment by rukundoeric** [comment]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯

- ### To Improve  
  - [x] [MANDATORY] When you run the tests, it mustn't ask for user inputs. Currently yours does, which is not correct. kindly fix it.

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Review by mricanho — APPROVED** [review]
# Status: ✔️ Project Approved ✔️ 

Hello team, good job on your rspecs! 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

You can contact me on slack if you have any questions, just search for me as @ Miguel Ricaño.

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

**Pull request merged**
